### ISSUE TITLE
is 'setuptools' required in __requires__ list?

### ISSUE THREAD

**Issue by anthrotype** [jaraco/rwt#11]
Hi @jaraco,
thanks for this great package!
I'm happily using it for bootstrapping build/test requirements in my setup.py, and replace `setup_requires` and `tests_requre` (I don't wanna compile cython into an .egg!)

Now, in the section `Replacing setup_requires` of your README.rst (btw, why isn't Github rendeing the ReStructuredText properly?), you recommend to add setuptools itself to the `__requires__` list.

I wonder, isn't this a bit redundant?
I can run `python -m rwt -- setup.py ...` just fine even if I don't explicitly add setuptools to `__requires__`.

Isn't setuptools a dependency of pip? And since rwt in turn needs pip to do its magic, if one uses rwt, one must also have pip and hence setuptools installed -- even only to install rwt in the first place.

I could see the use of it if, say, one requires a specific minimum version of setuptools.
But why requiring a generic one?

Sorry if my question sound stupid, and thanks again for the great work :)

**Comment by jaraco** [comment]
> why isn't Github rendeing the ReStructuredText properly?

There was a syntax problem in the source. I've corrected that.

> Is adding setuptools to __requires__ redundant?

Not exactly. Although pip installs setuptools and ensures setuptools is installed when running setup.py files for building, I don't think that's a guarantee on which you can rely, especially for direct invocation like running tests. In practice, you may be able to get away without specifying setuptools, but as this technique or others become more viable, I expect setuptools will become less of an implicit requirement and more explicit in usage.

Additionally, if you want to require a more (or older) version of setuptools, you can do that also in your `__requires__` directive.
