### ISSUE TITLE
Add a console entry point

### ISSUE THREAD

**Issue by pfmoore** [jaraco/rwt#8]
I gave this a try, and my immediate thought was to run it as "rwt". I know the docs say to use "python -m rwt", but maybe add a console entry point as a convenience?

**Comment by jaraco** [comment]
Sure - that's something I've been meaning to add for some time.

**Comment by pfmoore** [comment]
Would you like a (1-line!) PR or is it easy enough that you don't need me to bother?

**Comment by jaraco** [comment]
I can do it - looks like it needs to be more than one line because of the structure.

**Comment by jaraco** [comment]
Should release as 2.9 shortly.

**Comment by pfmoore** [comment]
Cool, thanks (I realised shortly after making my glib comment that it's only a 1-liner if you already had a main function...)
